_BASE_: "./base_ytvis.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: True
INPUT:
  FORMAT: "BGR"
